### PR TITLE
New H8D Utility version 2.2 features

### PR DESCRIPTION
**Pull request by DarrellH89**
New H8D Utility version 2.2 features
     Ability to create new disk images for H8D (100k), H37 (800k), H37(640k) CP/M format
     Ability to add files to existing disk images (H8D and H37). The previous version would create a new H8D image only.
     Convert between H37 and IMD formats
     Extract CP/M files from H8D, H37, and IMD disk images.
     Added view capability for H8D and H37 CP/M disk images
Notes:
     Converted IMD disk images only use full sectors. Sector compression is not supported
     File transfer process Windows to H89
          Create or open H37 disk image
          Add windows files to the H37 image
          Convert disk image to IMD format
          Use HxC Floppy Emulator software to convert to .HFE format
          Use .HFE file in Gotek/HxC floppy emulator on the H-89 hardware
     File transfer from H89 to Windows
          Use HxC Floppy Emulator software to convert HFE format to IMD
          Use H8DUtility to extract files from IMD image
               Convert to H37 format to add files

### CODE REVIEW

**Review by lesbird — CHANGES_REQUESTED** [review]
Darrell, you’ll also want to update the links in the html file (index.html) to point to your new zip (actually if you name the files the same and in the same folder you shouldn’t have to update the html at all). Also if you have a zip of the executable you should upload that as well and name it H8DUtility.zip. The current source file name is H8DUtilitySrc.zip so you should replace it with yours.

**Comment by lesbird** [comment]
So basically rename your source file to “H8DUtilitySrc.zip” and your executable to “H8DUtility.zip” and put them in the folder software/Utilities. I’ve already changed the link in index.html to point to these files.

**Comment by DarrellH89** [comment]
Les,
I uploaded my latest versions with the names H8DUtilitySrc.zip and executable to “H8DUtility.zip”.

Thanks,

  Darrell

**Comment by lesbird** [comment]
Ok Darrell, might have to push your changes and then the PR should update and I can then merge the changes.

**Comment by DarrellH89** [comment]
Les, I think I added it in the right place now.

 

  Darrell

**Review by lesbird — APPROVED** [review]

**Pull request merged**
